### ISSUE TITLE
Copy paste error in software update data

### ISSUE THREAD

**Issue by foosel** [markwal/OctoPrint-PortLister#1]
Update config is registered for gpx instead of portlister. I'm actually not sure right now what consequences that has when both plugins are installed, but they are surely bad and that should definitely be fixed. And I need to think of a way to allow multiple update configs in the hook but defaulting to the plugin identifier if there is only one or something like that.

**Comment by markwal** [comment]
Oooh.  Oops.

**Comment by markwal** [comment]
I think that fixed it.
