### ISSUE TITLE
Auto connect almost always errors out w/ Marlin 2.0-bugfixes

### ISSUE THREAD

**Issue by ej0rge** [markwal/OctoPrint-PortLister#13]
I'm not sure what might cause this. When i finally heard that portlister could automatically connect my printer after powering up via the psu control plugin, I wanted to try that. 

When i enable "auto-connect on server startup", it will automatically try to connect after i power up the printer, and after a while the connection will fail with a timeout error. In the log window it looks like it tried to connect and then at some point data stopped coming over the serial port. Usually right after the trinamic drivers report "OK" status. 

If i connect manually, it connects normally.

**Comment by hapklaar** [comment]
Not sure if you still have this issue, but it's working fine for me with latest versions of everything (Octoprint+plugins+Marlin bugfix-2.0.0)

**Comment by markwal** [comment]
Hopefully, it is fixed.  If not, for some it may be that the autoconnect delay needs to be increased and with the most recent release, you can now do that from Settings.

**Comment by ej0rge** [comment]
Saw the update. Thanks.
