### ISSUE TITLE
Constantly needs update

### ISSUE THREAD

**Issue by jeffeb3** [markwal/OctoPrint-PortLister#2]
I get the "Update Available" screen, and it's trying to update to 0.1.1, but it says successful whenever it finishes the update.

I have the 0.1.0.egg.info in oprint/lib/python2.7/site-packages/.

This is the octopi image, running on a raspberry pi 2.

**Comment by markwal** [comment]
Oops.  I forgot to update the internal version to match the tag.  That's what I get for only upgrading some of my projects to versioneer.

**Comment by jeffeb3** [comment]
Thanks, works.
