### ISSUE TITLE
config.yaml file

### ISSUE THREAD

**Issue by maukcc** [markwal/OctoPrint-PortLister#9]
When we installed, the config.yaml file was not updated automatically with the autoconnect_delay: 20
After we did this manually it worked like a charm.

**Comment by maukcc** [comment]
also when we change some settings and save, the config.yaml file gets overwritten and the autoconnect_delay: 20 is kicked out again

**Comment by markwal** [comment]
Thanks for the bug report.  I'll look into it.

**Comment by paccerdk** [comment]
The syntax/format is not clear on what to add to config.yaml, 
Since there are no defaults added, an example would be nice.
A menu would be even nicer ;)

**Comment by c3r63ru5** [comment]
Same issue here, using the latest Octopi distro with OctoPrint 1.3.6. Printer does not autoconnect when powered off and on again, and the settings are never automatically written in config.yaml and overwritten when manual set and Settings in the GUI are saved later.

**Comment by posicat** [comment]
Great plugin, I've got 2 printers and 2 instances of OctoPrint that have a PSU plugin.  It'd be nice if when the PSU turned on it could auto-connect, it doesn't seem to do it yet, but it does refresh.  Looks like similar issues to what folks are seeing here.

**Comment by davidsielert** [comment]
this is happening for me as well..

**Comment by nickbuhling** [comment]
I faced the same problem as @posicat. A settings page would be a very helpful improvement! Would love to see that added to the plugin.

**Comment by saschaludwig** [comment]
Any update?

**Comment by markwal** [comment]
Seems like I should add a settings page.  Perhaps in the next month or so.

**Comment by jeffnielson** [comment]
great.  looking forward to this.

**Comment by ccaramel** [comment]
Hi,
good job, the plugin I dreamed for.
Unfortunately the config lines in config.yaml not exists and if I enter them manually it disappears.
A upgrade for this would be appreciated.
Regards.

**Comment by markwal** [comment]
With 1.1.10, there's now a settings page that makes it easier to set the autoconnect_delay.  The reason people were have trouble before is that if you change the config.yaml while OctoPrint is running, OctoPrint will just stomp over it later (before it got a chance to read it).  So you'd have to stop the OctoPrint process, edit the config and then restart OctoPrint.  Now all that is moot though.  Hopefully.
